/**
 * Fingerprint canonicalisation, driven by the vectors shared across all eight
 * Tamga SDKs.
 *
 * `test/fixtures/fingerprint/fingerprint.json` is copied into the repo rather
 * than fetched, so the suite runs offline, and it was generated by an
 * independent SHA-256 implementation rather than by any SDK — a fixture an SDK
 * produced can only prove that SDK agrees with itself. Every positive vector
 * and every rejected case is iterated, so a vector added to the file is
 * exercised with no test edit.
 *
 * `canonical` in the file writes the U+001F unit separator as the display
 * placeholder `<US>`; {@link expand} puts the real byte back before comparing,
 * because it is the real byte that gets hashed.
 *
 * Beyond replaying the vectors, this file pins the three JavaScript-specific
 * ways a port of this algorithm goes wrong: `Array.prototype.sort` orders by
 * UTF-16 code unit rather than UTF-8 byte, `String.prototype.trim` strips the
 * Unicode whitespace set rather than the ASCII one, and
 * `String.prototype.normalize` sits right there tempting this port into being
 * the one that disagrees with the other seven.
 *
 * Every non-ASCII and control character below is written as an escape, never as
 * a literal: a raw U+001F or U+00A0 in a source file is invisible in a diff and
 * in review, which is exactly how a test pinning an invisible character gets
 * "tidied up" into passing vacuously.
 */

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";

import {
  canonicalFingerprintString,
  computeFingerprint,
  FINGERPRINT_DOMAIN,
  type FingerprintComponent,
} from "../src/fingerprint.js";
import { FingerprintError } from "../src/errors.js";

interface Vector {
  name: string;
  components: [string, string][];
  canonical: string;
  fingerprint: string;
  note: string;
}

interface RejectedCase {
  name: string;
  components: [string, string][];
  reason: string;
}

const vectorFile = JSON.parse(
  readFileSync(new URL("./fixtures/fingerprint/fingerprint.json", import.meta.url), "utf-8"),
) as { vectors: Vector[]; rejected: RejectedCase[] };

/** U+001F UNIT SEPARATOR — the real byte the fixture writes as `<US>`. */
const US = "\u001f";
/** U+0007 BELL — a control character that is not whitespace, so trimming cannot hide it. */
const BEL = "\u0007";
/** U+00A0 NO-BREAK SPACE — Unicode whitespace, but *not* ASCII whitespace. */
const NBSP = "\u00a0";
/** U+FFFF — the largest BMP code point: three UTF-8 bytes starting 0xEF. */
const BMP_MAX = "\uffff";
/** U+10000 — the smallest astral code point: four UTF-8 bytes starting 0xF0. */
const ASTRAL_MIN = "\u{10000}";

/**
 * The two orderings under discussion, written out locally so the test states
 * what it compares rather than reaching into the implementation.
 */
function compareByUtf8(a: string, b: string): number {
  const encoder = new TextEncoder();
  const left = encoder.encode(a);
  const right = encoder.encode(b);
  const shared = Math.min(left.length, right.length);
  for (let i = 0; i < shared; i++) {
    const diff = (left[i] as number) - (right[i] as number);
    if (diff !== 0) return diff;
  }
  return left.length - right.length;
}

/** What `Array.prototype.sort`'s default comparator does: UTF-16 code units. */
function compareByUtf16(a: string, b: string): number {
  return a < b ? -1 : a > b ? 1 : 0;
}

/** Replaces the fixture's display placeholder with the byte that is actually hashed. */
function expand(canonical: string): string {
  return canonical.split("<US>").join(US);
}

/** The fixture stores components as `[label, value]` pairs. */
function toComponents(pairs: [string, string][]): FingerprintComponent[] {
  return pairs.map(([label, value]) => ({ label, value }));
}

describe("the fixture is decoded as UTF-8", () => {
  /**
   * A sibling port shipped green locally and failed on `windows-latest` only,
   * because its file read used the platform locale codec (cp1252) and the `é`
   * in `non_ascii_value` decoded as mojibake — one SDK disagreeing with itself
   * across two operating systems, which is the failure the shared spec exists
   * to prevent arriving by a route the spec does not cover.
   *
   * Node's `readFileSync` is not locale-dependent, but it only returns a string
   * at all when handed an encoding, and this repo additionally runs its smoke
   * job on Deno and Bun. So the decode is asserted rather than assumed, and it
   * is asserted here — before any digest — so a mis-decode reports its own
   * cause instead of surfacing as an opaque hash mismatch.
   *
   * Every other vector is pure ASCII and would look green through a
   * mis-decoding reader. This one is the only load-bearing check.
   */
  it("reads the non-ASCII vector as the code points it actually contains", () => {
    const vector = vectorFile.vectors.find((v) => v.name === "non_ascii_value");
    expect(vector).toBeDefined();

    const value = (vector as Vector).components[0]?.[1];
    // U+0063 U+0061 U+0066 U+00E9 — four code points, NOT the five a cp1252
    // decode would produce ("cafÃ©").
    expect(value).toBe("caf\u00e9");
    expect(value).toHaveLength(4);
    expect(value?.codePointAt(3)).toBe(0x00e9);
  });

  it("round-trips the <US> placeholder to the real separator byte", () => {
    expect(expand("a<US>b")).toBe(`a${US}b`);
    expect(US.charCodeAt(0)).toBe(0x1f);
  });
});

describe("the shared positive vectors", () => {
  it("covers all nine, so a vector added to the fixture is not silently skipped", () => {
    expect(vectorFile.vectors).toHaveLength(9);
  });

  for (const vector of vectorFile.vectors) {
    describe(vector.name, () => {
      it(`canonicalises as stated — ${vector.note}`, () => {
        expect(canonicalFingerprintString(toComponents(vector.components))).toBe(
          expand(vector.canonical),
        );
      });

      it("hashes to the stated digest", () => {
        expect(computeFingerprint(toComponents(vector.components))).toBe(vector.fingerprint);
      });
    });
  }
});

describe("the shared rejected cases", () => {
  it("covers all eight", () => {
    expect(vectorFile.rejected).toHaveLength(8);
  });

  for (const rejected of vectorFile.rejected) {
    it(`rejects ${rejected.name} — ${rejected.reason}`, () => {
      // Both entry points must refuse: a caller reaching for the canonical
      // string to debug with must not get a value the hashing path refuses.
      expect(() => canonicalFingerprintString(toComponents(rejected.components))).toThrow(
        FingerprintError,
      );
      expect(() => computeFingerprint(toComponents(rejected.components))).toThrow(FingerprintError);
    });
  }
});

describe("the three invariants that carry the whole point", () => {
  const single = toComponents([["machine-id", "abc123"]]);

  it("is order-independent: caller order is convenience, not identity", () => {
    const sorted = toComponents([
      ["disk", "SN-9"],
      ["machine-id", "abc123"],
    ]);
    const unsorted = toComponents([
      ["machine-id", "abc123"],
      ["disk", "SN-9"],
    ]);

    expect(computeFingerprint(unsorted)).toBe(computeFingerprint(sorted));
  });

  it("absorbs surrounding ASCII whitespace: the trailing-newline footgun", () => {
    const padded = toComponents([["machine-id", "  abc123\t\n"]]);

    expect(computeFingerprint(padded)).toBe(computeFingerprint(single));
  });

  it("preserves case: lowercasing a base64 or hex identifier corrupts it", () => {
    const upper = toComponents([["machine-id", "ABC123"]]);

    expect(computeFingerprint(upper)).not.toBe(computeFingerprint(single));
  });
});

describe("the JavaScript-specific ways this goes wrong", () => {
  // Two candidates; only one of them is actually reachable. See each test.
  it("keeps the two comparators genuinely different on bare values", () => {
    // The control. UTF-8 puts the astral code point last (0xF0 > 0xEF); UTF-16
    // puts it first (0xD800 < 0xFFFF). If this ever stops holding, the
    // structural-equivalence claim below has lost its meaning.
    const utf8 = compareByUtf8(ASTRAL_MIN, BMP_MAX);
    const utf16 = compareByUtf16(ASTRAL_MIN, BMP_MAX);

    expect(Math.sign(utf8)).toBe(1);
    expect(Math.sign(utf16)).toBe(-1);
  });

  it("cannot reach that divergence, because the ASCII label always decides first", () => {
    // This is the honest form of "the sort is bytewise, not UTF-16". The
    // implementation IS bytewise, but no valid input distinguishes the two:
    // labels are ASCII printable and cannot contain `=`, and duplicates are
    // rejected, so two distinct components differ either at a label byte or at
    // the `=` terminating whichever label is a prefix of the other. Both are
    // below 0x80, where UTF-8 bytes and UTF-16 code units are identical.
    //
    // Asserting a divergence here instead would assert something false. What
    // this asserts is that the equivalence is structural — and it fails the
    // moment the label rules are relaxed enough to let a value decide an order.
    const labels = ["a", "z", "!", "~", "a0", "az", "zz", "machine-id", "disk", "m"];
    const values = [ASTRAL_MIN, BMP_MAX, "", "a", "\u00ff"];

    let compared = 0;
    for (const leftLabel of labels) {
      for (const rightLabel of labels) {
        if (leftLabel === rightLabel) continue; // duplicates are rejected
        for (const leftValue of values) {
          for (const rightValue of values) {
            const left = `${leftLabel}=${leftValue}`;
            const right = `${rightLabel}=${rightValue}`;
            compared++;
            expect(Math.sign(compareByUtf8(left, right))).toBe(
              Math.sign(compareByUtf16(left, right)),
            );
          }
        }
      }
    }

    expect(compared).toBe(2250);
  });

  it("sorts on the whole `label=value` component, not on the label alone", () => {
    // The discriminating shape: one label is a prefix of the other, and the
    // longer one's next character sorts BELOW '=' (0x3d). Here '-' is 0x2d.
    //
    //   whole component : "a-b=y" < "a=x"   ('-' 0x2d < '=' 0x3d)
    //   label only      : "a"     < "a-b"
    //
    // ...so the two orderings are exact reverses of each other, and a port that
    // sorts by label produces a different fingerprint for the same machine.
    const canonical = canonicalFingerprintString([
      { label: "a", value: "x" },
      { label: "a-b", value: "y" },
    ]);

    expect(canonical.split(US).slice(1)).toEqual(["a-b=y", "a=x"]);
  });

  it("sorts case-sensitively, so an uppercase label precedes a lowercase one", () => {
    // 'B' is 0x42 and 'a' is 0x61, so bytewise "B=2" comes first. A
    // case-insensitive comparator folds them and puts "a=1" first — the exact
    // reverse. Case folding anywhere in this algorithm is a defect (it also
    // corrupts base64 and hex values), and this is the ordering half of it.
    const canonical = canonicalFingerprintString([
      { label: "a", value: "1" },
      { label: "B", value: "2" },
    ]);

    expect(canonical.split(US).slice(1)).toEqual(["B=2", "a=1"]);
  });

  it("still sorts identically to the shared vectors' stated canonical order", () => {
    // `many` is the vector deliberately given out of byte order on input.
    const many = vectorFile.vectors.find((v) => v.name === "many");
    expect(many).toBeDefined();

    expect(canonicalFingerprintString(toComponents((many as Vector).components))).toBe(
      expand((many as Vector).canonical),
    );
  });

  it("trims the ASCII whitespace set, not the Unicode one", () => {
    // `String.prototype.trim` strips U+00A0. The other seven ports do not, so
    // neither may this one — the value has to survive as its UTF-8 bytes.
    const padded = `${NBSP}abc123${NBSP}`;
    expect(padded.trim()).toBe("abc123");

    const canonical = canonicalFingerprintString([{ label: "id", value: padded }]);

    expect(canonical).toBe(`${FINGERPRINT_DOMAIN}${US}id=${padded}`);
    expect(computeFingerprint([{ label: "id", value: padded }])).not.toBe(
      computeFingerprint([{ label: "id", value: "abc123" }]),
    );
  });

  it("does not Unicode-normalise, so the two forms of cafe stay different", () => {
    const composed = "caf\u00e9"; // NFC: e-acute as one code point
    const decomposed = "cafe\u0301"; // NFD: e + combining acute
    expect(composed.normalize("NFC")).toBe(decomposed.normalize("NFC"));

    expect(computeFingerprint([{ label: "owner", value: composed }])).not.toBe(
      computeFingerprint([{ label: "owner", value: decomposed }]),
    );
    // ...and the composed form is the one the shared `non_ascii_value` vector
    // states, so this SDK agrees with the other seven on which is which.
    expect(computeFingerprint([{ label: "owner", value: composed }])).toBe(
      "8a729bee74af4aeaf886d4584cc61bc8025d4bad3cce72441693e84e5c450739",
    );
  });
});

describe("rejections carry a matchable kind, and repair nothing", () => {
  function kindOf(components: FingerprintComponent[]): string {
    try {
      computeFingerprint(components);
    } catch (error) {
      if (error instanceof FingerprintError) return error.kind;
      throw error;
    }
    throw new Error("expected a FingerprintError");
  }

  it("names each failure", () => {
    expect(kindOf([])).toBe("no-components");
    expect(kindOf([{ label: "", value: "x" }])).toBe("empty-label");
    expect(kindOf([{ label: "a=b", value: "x" }])).toBe("invalid-label");
    expect(kindOf([{ label: "caf\u00e9", value: "x" }])).toBe("invalid-label");
    expect(kindOf([{ label: `a${US}b`, value: "x" }])).toBe("invalid-label");
    expect(
      kindOf([
        { label: "id", value: "a" },
        { label: "id", value: "b" },
      ]),
    ).toBe("duplicate-label");
    expect(kindOf([{ label: "id", value: `a${BEL}b` }])).toBe("invalid-value");
    expect(kindOf([{ label: "id", value: `a${US}b` }])).toBe("invalid-value");
  });

  it("reports the offending label so a caller can find it", () => {
    const error = (() => {
      try {
        computeFingerprint([
          { label: "disk", value: "ok" },
          { label: "disk", value: "also ok" },
        ]);
        return undefined;
      } catch (e: unknown) {
        return e;
      }
    })();

    expect(error).toBeInstanceOf(FingerprintError);
    expect((error as FingerprintError).label).toBe("disk");
  });

  it("rejects a control character rather than stripping it", () => {
    // Stripping would map `a<BEL>b` and `ab` onto one fingerprint, i.e. two
    // different machines onto one seat — the exact failure this module exists
    // to prevent, reintroduced by a well-meaning repair.
    expect(() => computeFingerprint([{ label: "id", value: `a${BEL}b` }])).toThrow(FingerprintError);
    expect(computeFingerprint([{ label: "id", value: "ab" }])).toHaveLength(64);
  });

  it("rejects a duplicate label rather than de-duplicating it", () => {
    expect(() =>
      computeFingerprint([
        { label: "id", value: "a" },
        { label: "id", value: "b" },
      ]),
    ).toThrow(FingerprintError);
  });

  it("accepts an empty value, which is not the same as an absent component", () => {
    expect(computeFingerprint([{ label: "machine-id", value: "" }])).toBe(
      "436082abfd4762981b51aa4067d4c4f32abbb85572d8ddb01e1793abe11a385a",
    );
    expect(computeFingerprint([{ label: "machine-id", value: "" }])).not.toBe(
      computeFingerprint([{ label: "machine-id", value: "abc123" }]),
    );
  });
});

describe("shape", () => {
  it("returns 64 lowercase hex characters", () => {
    const fingerprint = computeFingerprint([{ label: "machine-id", value: "abc123" }]);

    expect(fingerprint).toMatch(/^[0-9a-f]{64}$/);
  });

  it("starts every canonical string with the domain separator", () => {
    const canonical = canonicalFingerprintString([{ label: "machine-id", value: "abc123" }]);

    expect(canonical.startsWith(`${FINGERPRINT_DOMAIN}${US}`)).toBe(true);
  });

  it("is pure: the same components always give the same answer", () => {
    const components: FingerprintComponent[] = [
      { label: "machine-id", value: "abc123" },
      { label: "disk", value: "SN-9" },
    ];

    expect(computeFingerprint(components)).toBe(computeFingerprint(components));
  });
});
